# This script contains the code for two functions which seek to read a matrix value, compute its
#inverse and store its inverse value in cache for later use


#The makeCacheMatric function reads a matrix value and declares functions set, get ,setinv, getinv
# which respectively assign the matrix value to cache, return the matrix, assign the inverse value 
#to cache, return the #inverse value. These 4 functions are stored in a list which is the return value
#of the makeCacheMatrix function

makeCacheMatrix <- function(x = matrix()) {
  I<- NULL                       #initialize empty inverse value with NULL
  set <- function(y) {
    x <<- y                      #assign matrix to x
    I <<- NULL                   #assign NULL to I
  }
  get <- function() x            #returns the value of x     
  setinv <- function(inverse) I <<- inverse      #assign the inverse value to I
  getinv <- function() I         #returns the value of I
  list(set = set, get = get,     #list returned which contains 4 functions 
       setinv = setinv,
       getinv = getinv)
}


#cacheSolve reads the list generated by the former function and checks to see if the inverse has already
#been calculated and stored in the cache. If not, it computes the value and helps store the value in 
#cache for later use

cacheSolve <- function(x, ...) {
  I <- x$getinv()                #retrieves value of I stored in x
  if(!is.null(I)) {              #checks if inverse has already been calculated
    message("getting cached data")
    return(I)                    #if already calculated, prints above message and retrieves I
  }
  data <- x$get()                #retrieves the value of the matrix stored in x
  I <- solve(data, ...)          #computes the inverse of the matrix
  x$setinv(I)                    #assigns the computed value to I in the previous function
  I                              #returns computed value of inverse
}
